language: node_js
node_js:
  - "v10.15.1"

  
deploy:
  provider: script
  script: "cp .npmrc.template $HOME/.npmrc && npm publish"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:

    recipients:
    - alevel7@gmail.com
    on_success: change
    on_failure: always

after_success: npm run coverage

