language: node_js
node_js:
  - "v10.15.1"

  
deploy:
  provider: script
  script: "cp .npmrc.template $HOME/.npmrc && npm publish"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
    - julio@packagecloud.io
    on_success: change
    on_failure: always
    
before_install:
  - npm i -g npm@version-number