language: node_js
node_js:
  - "v10.15.1"

  
deploy:
  provider: script
  script: "cp .npmrc.template $HOME/.npmrc && npm publish"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: change
    on_failure: always

after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
